/**
 * Tables with CREATED_BY/MODIFYED_BY columns
 */
var tagged = ['FIELD_PHASE_DEVELOPMENT'
            , 'GLOBAL_ASSUMPTIONS'
            , 'CONTRACT_ADDITIONAL'
            , 'FIELD_ADDITIONAL'
            , 'LIQUID_PRICE'
            , 'GAS_PRICE'
            , 'INFLATION'
            , 'INV_ASS'
            , 'TAX_SYSTEM'
            , 'TAX_NODE'
            , 'FIELD_COMPLEX'
            , 'BLOCK_ADDITIONAL'
            , 'COMPANY_ADDITIONAL'];

// FIELD
node('FIELD_HEADER');
node('FIELD_ADDITIONAL', 'FIE_ID', 'FIELD_HEADER');
node('FIELD_CONTRACTS_BLOCKS', 'FIE_ID', 'FIELD_HEADER');
node('FIELD_PHASE_DEVELOPMENT', 'FIE_ID', 'FIELD_ADDITIONAL');
node('FIELD_RESERVOIRS', 'FIE_ID', 'FIELD_HEADER');
node('FIELD_RESV_LITHOLOGIES', 'FIE_ID', 'FIELD_HEADER');
node('PT_CON_CASH_FLOW_DATA', 'TAX_NODE_ID', 'TAX_NODE');
node('PT_DETAIL_CASH_FLOW_DATA', 'TAX_NODE_ID', 'TAX_NODE');
node('PT_DETAIL_CASH_FLOW_GROUP', 'TAX_NODE_ID', 'TAX_NODE');
node('PT_DETAIL_CASH_FLOW_TIMESERIES', 'TAX_NODE_ID', 'TAX_NODE');
node('PT_ECONOMIC_INDICATOR', 'TAX_NODE_ID', 'TAX_NODE');
node('PT_OTHER_INDICATOR', 'TAX_NODE_ID', 'TAX_NODE');
node('FIELD_ADDITIONAL', 'INV_ASS_ORIGINAL_ID', 'INV_ASS', 'INV_ASS_ID');
node('FIELD_ADDITIONAL', 'INV_ASS_REDIST_ID', 'INV_ASS', 'INV_ASS_ID');
node('FIELD_ADDITIONAL', 'TAX_NODE_ID', 'TAX_NODE');
node('INV_ASS_DATA', 'INV_ASS_ID', 'INV_ASS');
node('INV_ASS_TUPLE_DATA', 'INV_ASS_ID', 'INV_ASS');

make_backup_sql();
